# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
permalink:           pretty

# Setup
title:               mxaddict
tagline:             'Blog'
url:                 http://codedmaster.com
baseurl:             /

author:
  name:              'Barry Deeney'
  url:               http://codedmaster.com

paginate:            5

# Social media links
social:
  facebook:          mxaddict64
  github:            mxaddict
  gitlab:            mxaddict
  steam:             mxaddict
  twitter:           _mxaddict

# Gems
plugins:                [jekyll-paginate]

# We need to move our pages inside
include: [_pages]
