# Dependencies
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink:   pretty

# Setup
title:       mxaddict
tagline:     'Blog'
url:         http://codedmaster.com
base_url:    /

author:
  name:      'Barry Deeney'
  url:       http://codedmaster.com

paginate:    5

# Social media links
social:
  facebook:  mxaddicter
  github:    mxaddict
  gitlab:    mxaddict
  steam:     mxaddict
  twitter:   _mxaddict

# Gems
plugins:
  - jekyll-paginate
  - amp-jekyll

# Setup AMP for google
ampdir: amp

# We need to move our pages inside
include:
  - _pages
